### ISSUE TITLE
Diagnostic sorting is different between AnalyzerTest<T>.SortDistinctDiagnostics and IEnumerableExtensions.ToOrderedArray

### ISSUE THREAD

**Issue by vweijsters** [dotnet/roslyn-sdk#264]
There is a mismatch in the way that diagnostics are sorted in Analyzer<T>.SortDistinctDiagnostics ([link](https://github.com/dotnet/roslyn-sdk/blob/5873e5a1fc854389e1cb02a011bde22a701ce4a5/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L709)) and IEnumerableExtensions.ToOrderedArray ([link](https://github.com/dotnet/roslyn-sdk/blob/2e49116aa1db7af9a8c917913044cbab85cfb727/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Extensions/IEnumerableExtensions.cs#L11)).

The former one is called when verifying the found diagnostics ([link](https://github.com/dotnet/roslyn-sdk/blob/5873e5a1fc854389e1cb02a011bde22a701ce4a5/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L151)). The latter one is used when processing test code markup ([link](https://github.com/dotnet/roslyn-sdk/blob/1c9ea481ba3b843f2f05feecbee3421005687680/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/SolutionState.cs#L267))

The following test code shows the problem:
``` c#
        [Fact]
        [WorkItem(2902, "https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2902")]
        public async Task VerifyInvalidCodeConstructionsAsync()
        {
            var testCode = @"using System;
public class TestClass
{
    public static EventHandler[] TestMethod() => delegate { };
}
";

            DiagnosticResult[] expected =
            {
                Diagnostic().WithLocation(4, 50),
                DiagnosticResult.CompilerError("CS1660").WithMessage("Cannot convert anonymous method to type 'EventHandler[]' because it is not a delegate type").WithLocation(4, 50),
            };

            await VerifyCSharpDiagnosticAsync(testCode, expected, CancellationToken.None).ConfigureAwait(false);
        }
```
when added to the SA1130 unit tests in StyleCop.Analyzers ([link](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/09aa5be73750d41e3bebfdf40caefacd04e1c1ea/StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs#L16))

The produced output is:
```
Message: Expected diagnostic id to be "CS1660" was "SA1130"

Diagnostic:
    // Test0.cs(4,50): warning SA1130: Use lambda syntax
GetCSharpResultAt(4, 50, SA1130UseLambdaSyntax.SA1130)
```

Swapping the expected results does not make a difference.

**Comment by vweijsters** [comment]
@sharwell Can you have look? This blocks me from completing DotNetAnalyzers/StyleCopAnalyzers#2905.

**Comment by sharwell** [comment]
@vweijsters You can disambiguate the situation above by using `WithSpan` instead of `WithLocation` for both of the diagnostics.

**Comment by sharwell** [comment]
Currently the test framework sorts the expected and actual diagnostics, and then expects them to be in exactly the same order. This fails to account for overlapping spans that start at the some position _and are only validated by position_. The fix for the issue is to change the sequence-equality assertion to a check that does the following:

1. Attempt to match all expected diagnostics that specify a full span to actual diagnostics
2. Attempt to match all expected diagnostics that specify a location to actual diagnostics that did not match previously
3. Attempt to match all expected diagnostics that do not specify a location to actual diagnostics that did not match previously

If any expected or actual diagnostic remains unmatched, fail the test.
