### ISSUE TITLE
Automatically include all compiler diagnostics with IDs that match a provided code fix

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-sdk#419]
It's currently more difficult than expected to write a test for a code fix for a compiler suggestion or warning (#418). It would be good to automatically include all compiler diagnostics matching IDs supported by the code fix provider(s) used in the test.

**Comment by taori** [comment]
@sharwell Since this is tagged as "help wanted":

Which way would you want it implemented? I have identified GetSortedDiagnosticsAsync as the method to modify. Since CodeFixTest inherits from AnalyzerTest one obvious way would declaring a `protected virtual IsFiltered(Diagnostic diagnostic)` on AnalyzerTest, Call that method in `IsIncludedDiagnostic` and just override it in the CodeFixTest to match against the diagnostic id's in the present CodeFixProviders, since that class is aware of the given CodeFixProviders. 

Or would you prefer another way?

**Comment by sharwell** [comment]
That sounds reasonable
