### ISSUE TITLE
Implement a test framework for source generators

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-sdk#602]

**Comment by dcuccia** [comment]
This would be very helpful. I'm struggling to figure out what I'm doing wrong. At least some suggestion on how to bootstrap a basic InitializationContext and SourceGeneratorContext would let me confirm that my implementation code was working correctly.

**Comment by sharwell** [comment]
I'm pretty sure we can implement this similar to a CodeRefactoringProvider test, where `TestState` represents the initial code and `FixedState` represents the code with source generated code.

**Comment by naminodarie** [comment]
I have some requests.

https://github.com/dotnet/roslyn-sdk/blob/50e2a5526c05033b743d8835a259ca4d8851c441/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.SourceGenerators.Testing/SourceGeneratorTest%601.cs#L61-L79

1. Add GeneratedSources Property

It is hard to use `FixedCode` because `FixedState.Sources` needs original codes and generated codes.

I want an API like the below code.

```C#
        public SourceFileList GeneratedSources { get; }
        public override async Task RunAsync(CancellationToken cancellationToken = default)
        {
            // code
            var rawTestState = TestState.WithInheritedValuesApplied(null, fixableDiagnostics);
            var rawFixedState = FixedState.WithInheritedValuesApplied(rawTestState, fixableDiagnostics);

            foreach (var source in GeneratedSources)
            {
                if (source.content != null)
                {
                    rawFixedState.Sources.Add(source);
                }
            }
            // code
        }
```

2. Remove Verify.NotEmpty

Source generators can work in a project without any C# code.

https://github.com/dotnet/roslyn-sdk/blob/50e2a5526c05033b743d8835a259ca4d8851c441/samples/CSharp/SourceGenerators/SourceGeneratorSamples/CsvGenerator.cs

**Comment by sharwell** [comment]
@naminodarie can you file a follow-up issue for those? I forgot to close this issue when the library was initially added.
