### ISSUE TITLE
C# Analyzer - Unable to find package Microsoft.CodeAnalysis.VisualBasic.CodeFix.Testing.MSTest

### ISSUE THREAD

**Issue by kofifus** [dotnet/roslyn-sdk#604]
I am still unable to build the C# analyzer termplate in VS19 Version 16.8.0 Preview 2.1

I managed to create the project by creating a new user on my system with a very short name (which I personally think is an insane workaround)

However the project does not build I get:

> Error	NU1101	Unable to find package Microsoft.CodeAnalysis.VisualBasic.CodeFix.Testing.MSTest. No packages exist with this id in source(s): .Net Core Dev, ASP.NET Core Dev, dotnet.myget.org roslyn, nuget.org	

Any help ?

**Comment by sharwell** [comment]
The template automatically creates a **NuGet.config** file with this content alongside the solution:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="roslyn" value="https://dotnet.myget.org/F/roslyn/api/v3/index.json" />
    <add key="roslyn-analyzers" value="https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json" />
  </packageSources>
  <disabledPackageSources>
    <clear />
  </disabledPackageSources>
</configuration>
```

Based on the error message, this file is either missing, or Visual Studio has been reconfigured with a different set of package sources. The package listed above is available via the **roslyn-analyzers** feed listed in this file.

Note that _new_ packages will actually be published on the **dotnet-tools** feed instead of the MyGet feed listed here. I'll send a pull request to update the feeds.
