### ISSUE TITLE
GetTypeByMetadataName fails for ReadOnlyDictionary

### ISSUE THREAD

**Issue by j0shuams** [dotnet/roslyn-sdk#678]
I am trying to see if the return type of a method is the type `System.Collections.ObjectModel.ReadOnlyDictionary` by doing symbol equality check on the return type and the value returned by GetTypeByMetadataName

Here is a screenshot. I believe the call to GetTypeByMetadataName should be succeeding, but it returns null.

 
![gettype](https://user-images.githubusercontent.com/70237359/102699379-0d41a480-41f9-11eb-88d2-f5da98d766da.jpg)

In case it is relevant, here is the source code the context is built off of:

```csharp
using System.Collections.ObjectModel;
namespace Test
{
    public interface MyInterface
    {
        System.Collections.ObjectModel.ReadOnlyDictionary<int,int> MakeDictionaryt(int length);
    }
}
```

**Comment by j0shuams** [comment]
Same thing for ```System.Linq.Enumerable`1```

**Comment by sharwell** [comment]
`GetTypeByMetadataName` only returns a type if there is _exactly one_ type with the given name among the compilation and all its dependencies. Since this method doesn't consider accessibility, the most common failure case is having an `internal` type in a dependency with the same type name.

dotnet/roslyn-analyzers works around this design limitation by using a different lookup strategy:

https://github.com/dotnet/roslyn-analyzers/blob/9b181908a157b83cf8dcb672a3d07ad659416131/src/Utilities/Compiler/WellKnownTypeProvider.cs#L80-L164

**Comment by sharwell** [comment]
The semantics of `GetTypeByMetadataName` are defined in [dotnet/roslyn](https://github.com/dotnet/roslyn), so marking this one as external.
