### ISSUE TITLE
How to find variable value?

### ISSUE THREAD

**Issue by devlife** [dotnet/roslyn-sdk#882]
Is there a suggested way of getting the value of a variable? In my current code I have `ArgumentSyntax` and I need to get the value of the argument. 

For example:

```
var myClass = new MyClass();
var myVar = "my variable value";
var answer = myClass.DoSomething(myVar);
```

I have `myVar` as ArgumentSyntax but don't know if there is a definitive way of getting the value.

**Comment by svick** [comment]
In general, you can't, because doing that properly might require actually executing the code in question.

Though there are some special cases where doing this can work:

1. If `myVar` was actually a constant (`const string myVar`), you could get its "constant value":

   ```c#
   semanticModel.GetConstantValue(argument.Expression)
   ```

2. If the code in question is simple enough, it might make sense to write a very limited mini-interpreter for the kinds of C# code that you're expecting.

**Comment by RikkiGibson** [comment]
People sometimes use the scripting APIs to execute code on the fly, I think.

**Comment by devlife** [comment]
Very interesting. Thanks for the ideas!
