### ISSUE TITLE
Microsoft.CodeAnalysis.Testing support for incremental source generators

### ISSUE THREAD

**Issue by astaerk** [dotnet/roslyn-sdk#989]
As far as I can see Microsoft.CodeAnalysis.Testing only supports normal ISourceGenerator generators.
Are there any plans to support generators implementing IIncrementalGenerator?
Or are there any official alternatives for testing incremental source generators?

**Comment by sharwell** [comment]
Here's the verifier class for incremental source generator testing:
https://github.com/microsoft/vs-extension-testing/tree/main/src/Microsoft.VisualStudio.Extensibility.Testing.SourceGenerator.UnitTests/Verifiers

**Comment by astaerk** [comment]
Sorry for the late reply, I just realized, that I never posted the answer I had already written.

Thank you for that info. After I created my own verifier according to that example, I got a test running my generator. So that worked very well. The magic method seems to be 'AsSourceGenerator'.

The cookbook of the original source generators contains some info about testing: https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md
Maybe it would be helpful to also include some info about testing in the document for incremental generators: https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md

**Comment by xparadoxical** [comment]
I think this should be reopened. The support doesn't exist.

**Comment by sharwell** [comment]
@xparadoxical This support existed through a workaround previously, but was made official in #1084.

**Comment by xparadoxical** [comment]
Ohh, I see now. I ignored the dotnet-tools nuget feed installation [instruction](https://github.com/dotnet/roslyn-sdk/tree/main/src/Microsoft.CodeAnalysis.Testing#microsoftcodeanalysistesting) linked from the cookbook since it says "prerelease", but after some confusion, turns out (#1047) Nuget has the 2 years old v1.1.1 and v1.1.2 prereleases have the support.
For anyone who ever ends up here: [this csproj property](https://github.com/dotnet/roslyn-sdk/issues/1083#issuecomment-1496387254) is a nice way of adding it and [NugetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) is useful in determining a `Version` to use (but also a `NU` error tells what's the latest version when building).
